CREATE TABLE IF NOT EXISTS investments(
  id VARCHAR(36) PRIMARY KEY,
  amount DOUBLE PRECISION NOT NULL,
  annual_rate DOUBLE PRECISION NOT NULL,
  result DOUBLE PRECISION NOT NULL,
  annual_period INTEGER NOT NULL,
  created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
  deleted_at TIMESTAMP (6) WITHOUT TIME ZONE
);
